/**
 * __________________
 * Naming Convention:
 * ------------------
 * MODULE_NAME_ACTION_TYPE_DESCRIPTION: 'MODULE_NAME_ACTION_TYPE_DESCRIPTION'
 * Group actions from the same module together
 */

const types = {
    // auth related start
    AUTH_REGISTRATION_REQUESTING: 'AUTH_REGISTRATION_REQUESTING',
    AUTH_REGISTRATION_SUCCESS: 'AUTH_REGISTRATION_SUCCESS',
    AUTH_REGISTRATION_ERROR: 'AUTH_REGISTRATION_ERROR',
    AUTH_LOGIN_REQUESTING: 'AUTH_LOGIN_REQUESTING',
    AUTH_LOGIN_SUCCESS: 'AUTH_LOGIN_SUCCESS',
    AUTH_LOGIN_ERROR: 'AUTH_LOGIN_ERROR',
    AUTH_LOG_OUT: 'AUTH_LOG_OUT',
    AUTH_PASSWORD_RESET_EMAIL_REQUESTING: 'AUTH_PASSWORD_RESET_EMAIL_REQUESTING',
    AUTH_PASSWORD_RESET_EMAIL_SUCCESS: 'AUTH_PASSWORD_RESET_EMAIL_SUCCESS',
    AUTH_PASSWORD_RESET_EMAIL_ERROR: 'AUTH_PASSWORD_RESET_EMAIL_ERROR',
    AUTH_PASSWORD_RESET_REQUESTING: 'AUTH_PASSWORD_RESET_REQUESTING',
    AUTH_PASSWORD_RESET_SUCCESS: 'AUTH_PASSWORD_RESET_SUCCESS',
    AUTH_PASSWORD_RESET_ERROR: 'AUTH_PASSWORD_RESET_ERROR',
    AUTH_PASSWORD_RESET_RETRY: 'AUTH_PASSWORD_RESET_RETRY',
    AUTH_GET_ME: 'AUTH_GET_ME',
    AUTH_GET_ME_SUCCESS: 'AUTH_GET_ME_SUCCESS',
    AUTH_GET_ME_ERROR: 'AUTH_GET_ME_ERROR',
    AUTH_RESET_JUST_REGISTERED_VALUE: 'AUTH_RESET_JUST_REGISTERED_VALUE',
    // auth related end

    // profile related start
    PROFILE_SAVE_CARD_REQUESTING: 'PROFILE_SAVE_CARD_REQUESTING',
    PROFILE_SAVE_CARD_SUCCESS: 'PROFILE_SAVE_CARD_SUCCESS',
    PROFILE_SAVE_CARD_ERROR: 'PROFILE_SAVE_CARD_ERROR',
    PROFILE_SAVE_FIELD_REQUESTING: 'PROFILE_SAVE_FIELD_REQUESTING',
    PROFILE_SAVE_FIELD_SUCCESS: 'PROFILE_SAVE_FIELD_SUCCESS',
    PROFILE_SAVE_FIELD_ERROR: 'PROFILE_SAVE_FIELD_ERROR',
    // profile related end

    // message related start
    MESSAGE_RECEIVED: 'MESSAGE_RECEIVED',
    MESSAGE_EXPIRED: 'MESSAGE_EXPIRED',
    // message related end

    // users related start
    USERS_LIST_REQUESTING: 'USERS_LIST_REQUESTING',
    USERS_LIST_SUCCESS: 'USERS_LIST_SUCCESS',
    USERS_LIST_ERROR: 'USERS_LIST_ERROR',
    USERS_PAGE_REQUESTING: 'USERS_PAGE_REQUESTING',
    USERS_PAGE_SUCCESS: 'USERS_PAGE_SUCCESS',
    USERS_PAGE_ERROR: 'USERS_PAGE_ERROR',
    // users related end


    // cleanings related start
    CLEANINGS_TOGGLE_ADD_FORM: 'CLEANINGS_TOGGLE_ADD_FORM',
    CLEANINGS_NEW_REQUESTING: 'CLEANINGS_NEW_REQUESTING',
    CLEANINGS_NEW_SUCCESS: 'CLEANINGS_NEW_SUCCESS',
    CLEANINGS_NEW_ERROR: 'CLEANINGS_NEW_ERROR',
    CLEANINGS_LIST_REQUESTING: 'CLEANINGS_LIST_REQUESTING',
    CLEANINGS_LIST_SUCCESS: 'CLEANINGS_LIST_SUCCESS',
    CLEANINGS_LIST_ERROR: 'CLEANINGS_LIST_ERROR',
    CLEANINGS_CALENDAR_LIST_REQUESTING: 'CLEANINGS_CALENDAR_LIST_REQUESTING',
    CLEANINGS_CALENDAR_LIST_SUCCESS: 'CLEANINGS_CALENDAR_LIST_SUCCESS',
    CLEANINGS_CALENDAR_LIST_ERROR: 'CLEANINGS_CALENDAR_LIST_ERROR',
    CLEANINGS_CLEANER_LIST_REQUESTING: 'CLEANINGS_CLEANER_LIST_REQUESTING',
    CLEANINGS_CLEANER_LIST_SUCCESS: 'CLEANINGS_CLEANER_LIST_SUCCESS',
    CLEANINGS_CLEANER_LIST_ERROR: 'CLEANINGS_CLEANER_LIST_ERROR',
    CLEANINGS_PAGE_REQUESTING: 'CLEANINGS_PAGE_REQUESTING',
    CLEANINGS_PAGE_SUCCESS: 'CLEANINGS_PAGE_SUCCESS',
    CLEANINGS_PAGE_ERROR: 'CLEANINGS_PAGE_ERROR',
    CLEANINGS_UPDATE_REQUESTING: 'CLEANINGS_UPDATE_REQUESTING',
    CLEANINGS_UPDATE_SUCCESS: 'CLEANINGS_UPDATE_SUCCESS',
    CLEANINGS_UPDATE_ERROR: 'CLEANINGS_UPDATE_ERROR',
    CLEANING_ADD_FILTER: 'CLEANING_ADD_FILTER',
    CLEANING_REMOVE_FILTER: 'CLEANING_REMOVE_FILTER',

    // cleaning single page related
    CLEANINGS_SINGLE_REQUESTING: 'CLEANINGS_SINGLE_REQUESTING',
    CLEANINGS_SINGLE_SUCCESS: 'CLEANINGS_SINGLE_SUCCESS',
    CLEANINGS_SINGLE_ERROR: 'CLEANINGS_SINGLE_ERROR',
    // users related end

    // listings related
    LISTINGS_LIST_REQUESTING: 'LISTINGS_LIST_REQUESTING',
    LISTINGS_LIST_SUCCESS: 'LISTINGS_LIST_SUCCESS',
    LISTINGS_LIST_ERROR: 'LISTINGS_LIST_ERROR',

    // booking related
    BOOKINGS_TOGGLE_ADD_FORM: 'BOOKINGS_TOGGLE_ADD_FORM',
    BOOKINGS_NEW_REQUESTING: 'BOOKINGS_NEW_REQUESTING',
    BOOKINGS_NEW_SUCCESS: 'BOOKINGS_NEW_SUCCESS',
    BOOKINGS_NEW_ERROR: 'BOOKINGS_NEW_ERROR',
    BOOKINGS_LIST_REQUESTING: 'BOOKINGS_LIST_REQUESTING',
    BOOKINGS_LIST_SUCCESS: 'BOOKINGS_LIST_SUCCESS',
    BOOKINGS_LIST_ERROR: 'BOOKINGS_LIST_ERROR',
    BOOKINGS_CALENDAR_LIST_REQUESTING: 'BOOKINGS_CALENDAR_LIST_REQUESTING',
    BOOKINGS_CALENDAR_LIST_SUCCESS: 'BOOKINGS_CALENDAR_LIST_SUCCESS',
    BOOKINGS_CALENDAR_LIST_ERROR: 'BOOKINGS_CALENDAR_LIST_ERROR',
    BOOKINGS_PAGE_REQUESTING: 'BOOKINGS_PAGE_REQUESTING',
    BOOKINGS_PAGE_SUCCESS: 'BOOKINGS_PAGE_SUCCESS',
    BOOKINGS_PAGE_ERROR: 'BOOKINGS_PAGE_ERROR',
    BOOKINGS_UPDATE_REQUESTING: 'BOOKINGS_UPDATE_REQUESTING',
    BOOKINGS_UPDATE_SUCCESS: 'BOOKINGS_UPDATE_SUCCESS',
    BOOKINGS_UPDATE_ERROR: 'BOOKINGS_UPDATE_ERROR',
    BOOKINGS_ADD_FILTER: 'BOOKINGS_ADD_FILTER',
    BOOKINGS_REMOVE_FILTER: 'BOOKINGS_REMOVE_FILTER',

    // booking single
    BOOKINGS_SINGLE_REQUESTING: 'BOOKINGS_SINGLE_REQUESTING',
    BOOKINGS_SINGLE_SUCCESS: 'BOOKINGS_SINGLE_SUCCESS',
    BOOKINGS_SINGLE_ERROR: 'BOOKINGS_SINGLE_ERROR',

    // location related
    LOCATIONS_LIST_REQUESTING: 'LOCATIONS_LIST_REQUESTING',
    LOCATIONS_LIST_SUCCESS: 'LOCATIONS_LIST_SUCCESS',
    LOCATIONS_LIST_ERROR: 'LOCATIONS_LIST_ERROR',
    LOCATIONS_PAGE_REQUESTING: 'LOCATIONS_PAGE_REQUESTING',
    LOCATIONS_PAGE_SUCCESS: 'LOCATIONS_PAGE_SUCCESS',
    LOCATIONS_PAGE_ERROR: 'LOCATIONS_PAGE_ERROR',
    LOCATIONS_UPDATE_REQUESTING: 'LOCATIONS_UPDATE_REQUESTING',
    LOCATIONS_UPDATE_SUCCESS: 'LOCATIONS_UPDATE_SUCCESS',
    LOCATIONS_UPDATE_ERROR: 'LOCATIONS_UPDATE_ERROR',
    LOCATIONS_ADD_FILTER: 'LOCATIONS_ADD_FILTER',
    LOCATIONS_REPLACE_FILTER: 'LOCATIONS_REPLACE_FILTER',
    LOCATIONS_REMOVE_FILTER: 'LOCATIONS_REMOVE_FILTER',

    // location single
    LOCATIONS_SINGLE_REQUESTING: 'LOCATIONS_SINGLE_REQUESTING',
    LOCATIONS_SINGLE_SUCCESS: 'LOCATIONS_SINGLE_SUCCESS',
    LOCATIONS_SINGLE_ERROR: 'LOCATIONS_SINGLE_ERROR',
    LOCATIONS_UPLOAD_PHOTO_REQUESTING: 'LOCATIONS_UPLOAD_PHOTO_REQUESTING',
    LOCATIONS_UPLOAD_PHOTO_SUCCESS: 'LOCATIONS_UPLOAD_PHOTO_SUCCESS',
    LOCATIONS_UPLOAD_PHOTO_ERROR: 'LOCATIONS_UPLOAD_PHOTO_ERROR',
    LOCATIONS_DELETE_PHOTO_REQUESTING: 'LOCATIONS_DELETE_PHOTO_REQUESTING',
    LOCATIONS_DELETE_PHOTO_SUCCESS: 'LOCATIONS_DELETE_PHOTO_SUCCESS',
    LOCATIONS_DELETE_PHOTO_ERROR: 'LOCATIONS_DELETE_PHOTO_ERROR',

    // supplies related

    SUPPLIES_LIST_REQUESTING: 'SUPPLIES_LIST_REQUESTING',
    SUPPLIES_LIST_SUCCESS: 'SUPPLIES_LIST_SUCCESS',
    SUPPLIES_LIST_ERROR: 'SUPPLIES_LIST_ERROR',
    SUPPLIES_UPDATE_REQUESTING: 'SUPPLIES_UPDATE_REQUESTING',
    SUPPLIES_UPDATE_ERROR: 'SUPPLIES_UPDATE_ERROR',
    SUPPLIES_UPDATE_SUCCESS: 'SUPPLIES_UPDATE_SUCCESS',
    SUPPLIES_ADD_REQUESTING: 'SUPPLIES_ADD_REQUESTING',
    SUPPLIES_ADD_ERROR: 'SUPPLIES_ADD_ERROR',
    SUPPLIES_ADD_SUCCESS: 'SUPPLIES_ADD_SUCCESS',

    // supplies related
    SUPPLY_TRANSACTIONS_ADD_REQUESTING: 'SUPPLY_TRANSACTIONS_ADD_REQUESTING',
    SUPPLY_TRANSACTIONS_ADD_ERROR: 'SUPPLY_TRANSACTIONS_ADD_ERROR',
    SUPPLY_TRANSACTIONS_ADD_SUCCESS: 'SUPPLY_TRANSACTIONS_ADD_SUCCESS',
    SUPPLY_TRANSACTIONS_CHANGE_REQUESTING: 'SUPPLY_TRANSACTIONS_CHANGE_REQUESTING',
    SUPPLY_TRANSACTIONS_CHANGE_ERROR: 'SUPPLY_TRANSACTIONS_CHANGE_ERROR',
    SUPPLY_TRANSACTIONS_CHANGE_SUCCESS: 'SUPPLY_TRANSACTIONS_CHANGE_SUCCESS',

    // dashboard related
    DASHBOARD_CLEANINGS_LIST_REQUESTING: 'DASHBOARD_CLEANINGS_LIST_REQUESTING',
    DASHBOARD_CLEANINGS_LIST_SUCCESS: 'DASHBOARD_CLEANINGS_LIST_SUCCESS',
    DASHBOARD_CLEANINGS_LIST_ERROR: 'DASHBOARD_CLEANINGS_LIST_ERROR',
    DASHBOARD_CLEANINGS_UPDATE_REQUESTING: 'DASHBOARD_CLEANINGS_UPDATE_REQUESTING',
    DASHBOARD_CLEANINGS_UPDATE_SUCCESS: 'DASHBOARD_CLEANINGS_UPDATE_SUCCESS',
    DASHBOARD_CLEANINGS_UPDATE_ERROR: 'DASHBOARD_CLEANINGS_UPDATE_ERROR',
    DASHBOARD_UNASSIGNED_CLEANINGS_LIST_REQUESTING: 'DASHBOARD_UNASSIGNED_CLEANINGS_LIST_REQUESTING',
    DASHBOARD_UNASSIGNED_CLEANINGS_LIST_SUCCESS: 'DASHBOARD_UNASSIGNED_CLEANINGS_LIST_SUCCESS',
    DASHBOARD_UNASSIGNED_CLEANINGS_LIST_ERROR: 'DASHBOARD_UNASSIGNED_CLEANINGS_LIST_ERROR',
};

export default types;